<@compress single_line=true>
<response>
<resultCode>${resultCode}</resultCode>
<resultMsg>${resultMsg}</resultMsg>
<partyBrand>
<prodId>${result.PRODID!""}</prodId>
<partyId>${result.PARTYID!""}</partyId>
<custLevelName>${result.CUSTLEVELNAME!""}</custLevelName>
<custLevelId>${result.CUSTLEVELID!""}</custLevelId>
<partyName>${result.PARTYNAME!""}</partyName>
<identityNum>${result.IDENTITYNUM!""}</identityNum>
<identidiesTypeCd>${result.IDENTIDIESTYPECD!""}</identidiesTypeCd>
<contactPhone>${result.LINKPHONE!""} </contactPhone>
<inNetDate>${result.INNETDATE!""}</inNetDate>
<creditNumber>${result.CREDITNUMBER!""}</creditNumber>
<partyAddress>${result.ADDRESSSTR!""}</partyAddress>
<partyPost>${result.POSTCODE!""}</partyPost>
<partyStatus>${result.USERSTATUSCD!""}</partyStatus>
<greatLevel>${result.GREATLEVEL!""}</greatLevel>
<brandCode>${result.BRANDCODE!""}</brandCode>
<managerName>${result.MANAGERNAME!""}</managerName>
<vprepayFlag>${result.FEETYPE!""}</vprepayFlag>
<feeTypeCd>${result.FEETYPECD!""}</feeTypeCd>
<prodSpecId>${result.PRODSPECID!""}</prodSpecId>
<userType>${result.PARTYTYPE!""}</userType>
<userTypeId>${result.PARTYTYPEID!""}</userTypeId>
<offerSpecName>${result.OFFERNAME!""}</offerSpecName>
<offerSpecId>${result.OFFERSPECID!""}</offerSpecId>
</partyBrand>
</response>
</@compress>