<@compress single_line=true>
<response>
	<resultCode>${resultCode}</resultCode>
	<resultMsg>${resultMsg}</resultMsg>
	<preOrders>
	<#list result as p>
		<preOrder>
			<olId>${p.OL_ID!""}</olId>
			<partyName>${p.PARTY_NAME!""}</partyName>
			<channelId>${p.CHANNEL_ID!""}</channelId>
			<partyId>${p.PARTY_ID!""}</partyId>
			<statusCd>${p.STATUS_DT!""}</statusCd>
			<dt>${p.DT!""}</dt>
			<relaOlnbr>${p.RELA_OL_NBR!""}</relaOlnbr>
			<preType>${p.PRE_TYPE!""}</preType>
			<areaId>${p.AREA_ID}</areaId>
			<relaOlId>${p.RELA_OL_ID!""}</relaOlId>
			<channelName>${p.CHANNEL_NAME!""}</channelName>
			<staffId>${p.STAFF_ID!""}</staffId>
			<areaName>${p.AREA_NAME!""}</areaName>
			<statusCd>${p.STATUS_CD!""}</statusCd>
			<staffName>${p.STAFF_NAME!""}</staffName>
			<delDt>${p.DEL_DT!""}</delDt>
			<olNbr>${p.OL_NBR!""}</olNbr>
			<olTypeCd>${p.OL_TYPE_CD!""}</olTypeCd>
			<statusName>${p.STATUS_NAME!""}</statusName>
			<offerSpecName>${p.offerSpec.NAME!""}</offerSpecName>
			<offerSpecId>${p.offerSpec.OFFER_SPEC_ID!""}</offerSpecId>
		</preOrder>
	</#list>
	</preOrders>
</response>
</@compress>
