 <request>
    <channelId>${channelId!""}</channelId>
    <staffCode>${staffCode!""}</staffCode>
    <areaId/>
    <order>
      <orderTypeId>${orderTypeId!""}</orderTypeId>
      <partyId>${partyId!""}</partyId>
      <prodSpecId>${prodSpecId!""}</prodSpecId>
      <prodId>${prodId!""}</prodId>
      <systemId>${systemId!""}</systemId> 
      <chargeInfo>
        <appCharge>${appCharge!""}</appCharge>
        <charge>${charge!""}</charge>
      </chargeInfo>
      <tds>
        <td>
          <devModelId>${devModelId!""}</devModelId>
          <devNumId>${devNumId!""}</devNumId>
          <maintainTypeCd>${maintainTypeCd!""}</maintainTypeCd>
          <ownerTypeCd>${ownerTypeCd!""}</ownerTypeCd>
          <terminalCode>${terminalCode!""}</terminalCode>
          <terminalDevId>${terminalDevId!""}</terminalDevId>
          <terminalDevSpecId>${terminalDevSpecId!""}</terminalDevSpecId>
        </td>
      </tds>
    </order>
 </request>