<@compress single_line=true>
<response>
<resultCode>${resultCode}</resultCode>
<resultMsg>${resultMsg}</resultMsg>
<ticketList>
<#list ticketList.ticketList as c>
<ticketInfo>
<auditTicketName>${c.auditTicketName!""}</auditTicketName>
<auditTicketCd>${c.auditTicketCd!""}</auditTicketCd>
<auditTicketId>${c.auditTicketId!""}</auditTicketId>
<auditTicketType>${c.auditTicketType!""}</auditTicketType>
<areaId>${c.areaId!""}</areaId>
<price>${c.price!""}</price>
<createDt>${c.createDt!""}</createDt>
<startDt>${c.startDt!""}</startDt>
<endDt>${c.endDt!""}</endDt>
<statusCd>${c.statusCd!""}</statusCd>
<statusName>${c.statusName!""}</statusName>
<boId>${c.boId!""}</boId>
<partyId>${c.partyId!""}</partyId>
<partyName>${c.partyName!""}</partyName>
<channelId>${c.channelId!""}</channelId>
<staffId>${c.staffId!""}</staffId>
<staffName>${c.staffName!""}</staffName>
<channelName>${c.channelName!""}</channelName>
<accessNumber>${c.accessNumber!""}</accessNumber>
<offerSpecId>${c.offerSpecId!""}</offerSpecId>
<offerId>${c.offerId!""}</offerId>
<offerName>${c.offer_name!""}</offerName>
<ruleCfgId>${c.ruleCfgId!""}</ruleCfgId>
<bcdCode>${c.bcd_code!""}</bcdCode>
<materialName>${c.material_name!""}</materialName>
<operationType>${c.operation_type!""}</operationType>
</ticketInfo>
</#list>
</ticketList>
</response>
</@compress>