/**
 * WSSPortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.linkage.bss.crm.ws.csb;

public interface WSSPortType extends java.rmi.Remote {
    public java.lang.String login(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String confirmCertGift(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkPassword(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String changePassword(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String resetPassword(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryService(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getBrandLevelDetail(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String queryNbrByIccid(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String isYKSXInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String newValidateService(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryAccNBRInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryAreaInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryOperatingOfficeInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String businessService(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String modifyCustom(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryFNSInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryContinueOrderPPInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String confirmContinueOrderPPInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryOperation(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryPpInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryOffering2Pp(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryAgentInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkTicket(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String confirmSequence(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String checkSequence(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkSaleResourceByCode(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryCouponInfoByPriceplan(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryUserScore(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryUserScoreDetail(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String exchangeUserScore(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkGlobalroam(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String selectPartyManager(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String selectPartyInfo(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String checkCampusUser(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryImsiInfoByMdn(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryProdinfoByImsi(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String createCRAccount(java.lang.String srcDeviceID, int subscribeFrom, java.lang.String userID, java.lang.String userPayType, int userType) throws java.rmi.RemoteException;
    public java.lang.String delCRAccount(java.lang.String srcDeviceID, int subscribeFrom, java.lang.String userID, java.lang.String userPayType, int userType) throws java.rmi.RemoteException;
    public java.lang.String qryUserScoreDetailAll(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String adjustUserScore(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String validateAuditTicket(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String allocAuditTickets(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String releaseAuditTickets(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String exchangeAuditTickets(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryOrderListInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String blackUserCheck(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String goodsBatchGet(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String cancelOrder(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryUserVipType(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getCustAdInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String filterNumber(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String createCust(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkUimNo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryCust(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getCheckResult(java.lang.String serialNo, java.lang.String msgname, java.lang.String msgid) throws java.rmi.RemoteException;
    public java.lang.String queryPhoneNumberPoolList(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryPhoneNumberList(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String isSubsidy(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String presentUserScore(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getPreInterimBycond(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryPreOrderDetail(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String updatePreInterim(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryTml(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String createUserAddr(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String initStaticData(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryProd(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String orderSubmit(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryBuilding(java.lang.String buildingId, java.lang.String code, java.lang.String name, java.lang.String address, int currentPage) throws java.rmi.RemoteException;
    public java.lang.String querySerivceAcct(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String addSerivceAcct(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String createBroadbandAccount(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryProdByCompProdSpecId(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String compProdRule(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String generateCoNbr(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkBindAccessNumber(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryPricePlanService(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryAcctInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkPartyProd(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String isAlive() throws java.rmi.RemoteException;
    public java.lang.String addressForRoomList(java.lang.String snNumber, java.lang.String address, java.lang.String searchType, java.lang.String pageNum) throws java.rmi.RemoteException;
    public java.lang.String phoneForRoomList(java.lang.String snNumber, java.lang.String phoneNumber, java.lang.String searchType, java.lang.String pageNum) throws java.rmi.RemoteException;
    public java.lang.String queryForPortList(java.lang.String snNumber, java.lang.String addressID, java.lang.String searchType) throws java.rmi.RemoteException;
    public java.lang.String crmPreUse(java.lang.String snNumber, java.lang.String searchType, java.lang.String addressID, java.lang.String userAddress, java.lang.String interType) throws java.rmi.RemoteException;
    public java.lang.String getUimCardInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryPreLock(java.lang.String inXml) throws java.rmi.RemoteException;
    public java.lang.String rscNumberPreUse(java.lang.String inXml) throws java.rmi.RemoteException;
    public java.lang.String rscNumberQuery(java.lang.String qryCondition) throws java.rmi.RemoteException;
    public java.lang.String rscLoverNumberQuery(java.lang.String qryCondition) throws java.rmi.RemoteException;
    public java.lang.String getPUK(java.lang.String qryCondition) throws java.rmi.RemoteException;
    public java.lang.String queryProjProcessInfo(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String queryManager(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String qryPreHoldNumber(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String qryCSUserScoreDetailAll(java.lang.String msgText) throws java.rmi.RemoteException;
    public java.lang.String checkExchangeTicket(java.lang.String msgText) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.AccountQueryReturn accountQuery(com.linkage.bss.crm.ws.csb.AccountQueryType request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.QryIsOweReturn qryIsOwe(com.linkage.bss.crm.ws.csb.QryIsOweType request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.PrepayCanBackReturnType prepayCanBack(com.linkage.bss.crm.ws.csb.PrepayCanBackType request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.TransBalanceQueryReturn transBalanceQuery(com.linkage.bss.crm.ws.csb.TransBalanceQueryType request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.BalanceTransferReturn balanceTransfer(com.linkage.bss.crm.ws.csb.BalanceTransferType request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.CardManageResp cardManage(com.linkage.bss.crm.ws.csb.CardManageReq request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.QueryFillResp crmFillRecord(com.linkage.bss.crm.ws.csb.QueryFillReq request) throws java.rmi.RemoteException;
    public com.linkage.bss.crm.ws.csb.QueryCardResp queryCardRecord(com.linkage.bss.crm.ws.csb.QueryCardReq request) throws java.rmi.RemoteException;
    public void indentInvoiceNumQry(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, int cycleId, java.lang.String staffId, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result, javax.xml.rpc.holders.StringHolder invoiceNbr, javax.xml.rpc.holders.StringHolder receiptNbr) throws java.rmi.RemoteException;
    public void indentItemSync(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, java.lang.String channelId, int cycleId, javax.xml.rpc.holders.StringHolder payIndentId, java.lang.String custType, java.lang.String custId, java.lang.String custName, java.lang.String staffId, com.linkage.bss.crm.ws.csb.ItemType[] itemList, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public void indentItemPay(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, java.lang.String channelId, int cycleId, java.lang.String payIdentId, java.lang.String custType, java.lang.String custId, java.lang.String custName, java.lang.String staffId, java.lang.String interfaceSerial, com.linkage.bss.crm.ws.csb.PayItemType[] itemList, com.linkage.bss.crm.ws.csb.PayInfoType[] payList, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.StringHolder payIndentId, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public void batchIndentItemSync(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, java.lang.String channelId, java.lang.String cycleId, javax.xml.rpc.holders.StringHolder payIndentId, java.lang.String agentId, java.lang.String agentName, java.lang.String totalCharge, java.lang.String totalChargeGet, java.lang.String totalCount, java.lang.String staffId, com.linkage.bss.crm.ws.csb.BatchSyncItemType[] itemList, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public void indentInvoicePrint(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, int cycleId, javax.xml.rpc.holders.StringHolder payIndentId, java.lang.String staffId, int printType, int invoiceType, java.lang.String invoiceId, java.lang.String channelId, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result, com.linkage.bss.crm.ws.csb.holders.ArrayOf_tns4_InvoiceListTypeHolder invoiceLists) throws java.rmi.RemoteException;
    public void indentInvoiceNumMod(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, int cycleId, java.lang.String staffId, int invoiceType, java.lang.String invoiceId, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public void prepayBack(java.lang.String requestId, java.lang.String requestTime, java.lang.String servId, java.lang.String acctId, java.lang.String instanceId, java.lang.String platId, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result, com.linkage.bss.crm.ws.csb.holders.ArrayOf_tns4_BalanceListTypeHolder balanceList) throws java.rmi.RemoteException;
    public void terminalExchangeSync(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, int cycleId, java.lang.String exchangeDate, java.lang.String staffId, java.lang.String channelId, java.lang.String payIndentId, int charge, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public void agentIndentItemSync(java.lang.String requestId, java.lang.String requestTime, java.lang.String platId, int cycleId, javax.xml.rpc.holders.StringHolder payIndentId, int agentId, java.lang.String agentCode, java.lang.String agentName, java.lang.String staffCode, com.linkage.bss.crm.ws.csb.Item[] itemList, javax.xml.rpc.holders.StringHolder responseId, javax.xml.rpc.holders.StringHolder responseTime, javax.xml.rpc.holders.IntHolder result) throws java.rmi.RemoteException;
    public java.lang.String eai2Lan(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkGiftCert(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String computeChargeInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String queryMdnByUim(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getUserZJInfoByAccessNumber(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String validateContractInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String qryCreditrating(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkDeviceId(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkSnPwd(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String transmitRandom(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkDeviceIdNew(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getClerkId(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String GDYHgetOrRelease(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String highFeeQueryUserInfo(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String indentPayNotice(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String checkResultIn(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String getOnuLoid(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String insertPoint(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String updateAndConfirmPoint(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String insertPointRefund(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String changeStaffPassword(java.lang.String request) throws java.rmi.RemoteException;
    public java.lang.String syncDate4Prm2Crm(java.lang.String request) throws java.rmi.RemoteException;
}
