<@compress single_line=true>
<response>
<RESULT>${resultMap.RESULT!""}</RESULT>
<CAUSE>${resultMap.CAUSE!""}</CAUSE>
<TERMINAL_DEV_ID>${resultMap.TERMINAL_DEV_ID!""}</TERMINAL_DEV_ID>
<TERMINAL_CODE>${resultMap.TERMINAL_CODE!""}</TERMINAL_CODE>
<DEV_MODEL_NAME>${resultMap.DEV_MODEL_NAME!""}</DEV_MODEL_NAME>
<C_IMSI>${resultMap.C_IMSI!""}</C_IMSI>
<IMSI_STATE>${resultMap.IMSI_STATE!""}</IMSI_STATE>
<G_IMSI>${resultMap.G_IMSI!""}</G_IMSI>
<C_AKEY>${resultMap.C_AKEY!""}</C_AKEY>
<G_AKEY>${resultMap.G_AKEY!""}</G_AKEY>
<HRPD_UPP>${resultMap.HRPD_UPP!""}</HRPD_UPP>
<HRPD_SS>${resultMap.HRPD_SS!""}</HRPD_SS>
<STORE_NAME>${resultMap.STORE_NAME!""}</STORE_NAME>
<HLR_CODE>${resultMap.HLR_CODE!""}</HLR_CODE>
<UIMID>${resultMap.UIMID!""}</UIMID>
<ISEVDO>${resultMap.ISEVDO!""}</ISEVDO>
<ESN>${resultMap.ESN!""}</ESN>
<ICCID>${resultMap.ICCID!""}</ICCID>
<PUK1>${resultMap.PUK1!""}</PUK1>
<PUK2>${resultMap.PUK2!""}</PUK2>
<PIN1>${resultMap.PIN1!""}</PIN1>
<PIN2>${resultMap.PIN2!""}</PIN2>
</response>
</@compress>