<@compress single_line=true>
<response>
<resultCode>${resultCode}</resultCode>
<resultMsg>${resultMsg}</resultMsg>
<custOrderList>
<zongNum>${zongNum!""}</zongNum>
<noCnum>${noCnum!""}</noCnum>
<#list paramList as c>
	<custOrder>
		<olId>${c.OL_ID!""}</olId>
		<olNbr>${c.OL_NBR!""}</olNbr>
		<areaName>${c.AREANAME!""}</areaName>
		<accessNumber>${c.ACCESS_NUMBER!""}</accessNumber>
		<payIndentId>${c.PAY_INDENT_ID!""}</payIndentId>
		<soDate>${c.SO_DATE}</soDate>
		<soStatusDt>${c.STATUS_DT}</soStatusDt>
		<statusCd>${c.STATUS_CD!""}</statusCd>
		<charge>${c.charge1!""}</charge>
		<partyName>${c.PARTY_NAME!""}</partyName>
		<statusName>${c.STATUS_NAME!""}</statusName>
		<olTypeCd>${c.OL_TYPE_CD!""}</olTypeCd>
		<olTypeName>${c.OL_TYPE_NAME!""}</olTypeName>
		<staffName>${c.STAFF_NAME!""}</staffName>
		<staffNumber>${c.STAFF_NUMBER!""}</staffNumber>
		<channelName>${c.CHANNEL_NAME!""}</channelName>
		<channelManageCode>${c.MANAGER_CODE!""}</channelManageCode>
		<boInfos>
			<#list c.boInfos as boinfo>
			<boInfo>
				<boId>${boinfo.BO_ID!""}</boId>
			    <name>${boinfo.NAME!""}</name>
			    <boActionTypeName>${boinfo.DESC1!""}</boActionTypeName>
			</boInfo>
			</#list>
		</boInfos>
	</custOrder>
</#list>
</custOrderList>
</response>
</@compress>